<a href="https://colab.research.google.com/github/Maria-Ul/Inverse-Scattering-Problem/blob/master/data_generator_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install PyMieScatt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting PyMieScatt
  Downloading PyMieScatt-1.8.1.1.tar.gz (14 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from PyMieScatt) (1.21.6)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from PyMieScatt) (1.7.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from PyMieScatt) (3.2.2)
Requirement already satisfied: shapely in /usr/local/lib/python3.7/dist-packages (from PyMieScatt) (1.8.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->PyMieScatt) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->PyMieScatt) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->PyMieScatt) (1.4.4)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->PyMieScatt) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib->PyMieScatt) (4.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib->PyMieScatt) (1.15.0)
Building wheels for collected packages: PyMieScatt
  Building wheel for PyMieScatt (setup.py) ... done
  Created wheel for PyMieScatt: filename=PyMieScatt-1.8.1.1-py3-none-any.whl size=14975 sha256=55479bf99ac223a75a8f2644b5d2439ba6ce3929ec2398c573955d1ae8716a3c
  Stored in directory: /root/.cache/pip/wheels/b5/8d/db/bd1d433522603bd1fa0c712d44fb12310f9b768590cadbb700
Successfully built PyMieScatt
Installing collected packages: PyMieScatt
Successfully installed PyMieScatt-1.8.1.1

In [ ]:
import PyMieScatt as ps
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
import math

In [ ]:
env_refractive_index = 1.333
wavelength = 660  # nm wavelength

In [ ]:
theta, _, _, scatter_unpolarized = ps.ScatteringFunction(
                                        m = 1.1,  # particle refractive index
                                        wavelength = 660,
                                        diameter = 5.4,  # in nanometrs
                                        nMedium = 1.0,  # refractive index of enviroment
                                        minAngle = 10,
                                        maxAngle = 65,
                                        angularResolution = 55 / 256,
                                        space = 'theta',
                                        angleMeasure = 'degrees',
                                        normalization = None
                                    )

In [ ]:
database = pd.DataFrame(columns=['rel_r_i', 'size'] + list(theta))
database

Empty DataFrame
Columns: [rel_r_i, size, 10.0, 10.21484375, 10.4296875, 10.64453125, 10.859375, 11.07421875, 11.2890625, 11.50390625, 11.71875, 11.93359375, 12.1484375, 12.36328125, 12.578125, 12.79296875, 13.0078125, 13.22265625, 13.4375, 13.65234375, 13.8671875, 14.08203125, 14.296875, 14.51171875, 14.7265625, 14.94140625, 15.15625, 15.37109375, 15.5859375, 15.80078125, 16.015625, 16.23046875, 16.4453125, 16.66015625, 16.875, 17.08984375, 17.3046875, 17.51953125, 17.734375, 17.94921875, 18.1640625, 18.37890625, 18.59375, 18.80859375, 19.0234375, 19.23828125, 19.453125, 19.66796875, 19.8828125, 20.09765625, 20.3125, 20.52734375, 20.7421875, 20.95703125, 21.171875, 21.38671875, 21.6015625, 21.81640625, 22.03125, 22.24609375, 22.4609375, 22.67578125, 22.890625, 23.10546875, 23.3203125, 23.53515625, 23.75, 23.96484375, 24.1796875, 24.39453125, 24.609375, 24.82421875, 25.0390625, 25.25390625, 25.46875, 25.68359375, 25.8984375, 26.11328125, 26.328125, 26.54296875, 26.7578125, 26.97265625, 27.1875, 27.40234375, 27.6171875, 27.83203125, 28.046875, 28.26171875, 28.4765625, 28.69140625, 28.90625, 29.12109375, 29.3359375, 29.55078125, 29.765625, 29.98046875, 30.1953125, 30.41015625, 30.625, 30.83984375, ...]
Index: []

[0 rows x 259 columns]

In [ ]:
for i in range(20000):
  n = random.uniform(1.01,1.23)
  x = random.uniform(11,100)
  _, _, _, scatter_unpolarized = ps.ScatteringFunction(
                                        m = n*env_refractive_index,  # particle refractive index
                                        wavelength = 660,
                                        diameter = x/(1.333*math.pi/0.66)*1000,  # in nanometrs
                                        nMedium = env_refractive_index,  # refractive index of enviroment
                                        minAngle = 10,
                                        maxAngle = 65,
                                        angularResolution = 55 / 256,
                                        space = 'theta',
                                        angleMeasure = 'degrees',
                                        normalization = None
                                    )

  database.loc[i] = [n, x] + list(scatter_unpolarized)

In [ ]:
len(database)

In [ ]:
database.to_csv('/content/drive/MyDrive/Scattering_Group/PyMieScatt/train_data_100k.csv')

In [ ]:
database

,rel_r_i,size,10.0,10.21484375,10.4296875,10.64453125,10.859375,11.07421875,11.2890625,11.50390625,...,63.06640625,63.28125,63.49609375,63.7109375,63.92578125,64.140625,64.35546875,64.5703125,64.78515625,65.0
0,1.057872,74.691437,38260.571043,42962.689557,50768.742342,58364.394554,62904.089741,62713.205088,57608.885858,48791.932887,...,156.887533,151.438457,134.926567,111.794569,88.141828,70.112849,62.303583,66.597545,81.723890,103.637193
1,1.205170,24.976071,521.345595,525.206603,572.972924,655.404023,764.603526,893.886606,1037.634302,1191.141666,...,74.711194,69.547255,64.087573,58.485379,52.899404,47.488698,42.407396,37.799600,33.794561,30.502313
2,1.095671,34.348544,14003.785811,11869.131795,10211.443351,9037.349067,8328.567643,8044.994028,8128.651561,8508.244780,...,44.341761,40.186235,35.747432,31.273948,27.011047,23.186639,19.998593,17.604073,16.111471,15.575302
3,1.074263,99.250489,40507.110022,31843.276296,35984.753149,49211.924093,64464.323041,74393.775714,74408.616852,64439.504176,...,179.492549,224.191541,237.267951,212.317929,160.935334,107.779105,79.230999,90.814975,139.357309,203.840168
4,1.182280,39.481018,9787.642549,11150.656819,12752.258034,14454.586216,16122.931936,17633.960170,18882.572485,19787.092425,...,44.901259,49.237900,56.674981,66.206599,76.716100,87.083702,96.287299,103.487484,108.089860,109.780260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,1.198395,90.289496,42776.770808,58404.436796,71117.511747,77811.176248,76783.825465,68387.319786,55074.493607,40761.455183,...,307.019750,221.920489,145.011300,100.898135,100.092400,136.818745,192.805058,244.946226,273.698970,269.294341
19996,1.070573,17.112283,4349.596172,3849.311801,3389.527858,2969.176663,2587.028471,2241.707759,1931.709944,1655.418370,...,4.980174,4.938468,4.869286,4.773865,4.653768,4.510853,4.347236,4.165260,3.967454,3.756492
19997,1.206958,92.807700,48100.809106,31326.936802,20636.157230,16918.359570,19564.091024,26869.633406,36503.825334,45951.304091,...,343.290578,222.009246,152.108759,155.558230,222.600404,318.398492,399.456506,432.148371,405.498060,333.484923
19998,1.058556,96.735695,115809.538439,115285.073164,100405.649052,77335.959549,55307.093451,42302.681043,41659.385116,51008.045681,...,193.879544,253.640872,298.182576,308.900831,282.136953,230.468837,176.975493,145.105284,148.602884,185.812589
19999,1.123427,85.062518,27771.701905,29259.407557,37909.794648,51180.215416,65237.968608,76052.676116,80571.107670,77608.152959,...,126.730179,97.434199,62.237985,33.908252,23.485458,35.530686,65.790328,102.433862,130.535245,138.057909

In [ ]:
database['size'].hist()

In [ ]:
database.to_csv('/content/drive/MyDrive/Scattering_Group/PyMieScatt/train_data_100k.csv')